### ISSUE TITLE
Pagination in Modal

### ISSUE THREAD

**Issue by sandervercampt** [emargareten/inertia-modal#23]
Hi,

I have an issue with pagination in the modal.  
On first render of the modal the data seems to be ok:
<img width="596" alt="Screenshot 2024-03-07 at 14 28 09" src="https://github.com/emargareten/inertia-modal/assets/8994894/9320873b-0b75-488e-aacc-6564d0bafa87">

But when I try to paginate, the request is ok, but the returned data is not ok:
<img width="550" alt="Screenshot 2024-03-07 at 14 28 19" src="https://github.com/emargareten/inertia-modal/assets/8994894/5b3fdfd0-d8fb-45af-9d5e-89ddf62c1e04">

Error:
<img width="816" alt="Screenshot 2024-03-07 at 14 28 31" src="https://github.com/emargareten/inertia-modal/assets/8994894/516ed926-c753-47df-b0d6-54827fbb9b08">

Any idea how I can fix this? Thanks!

**Comment by emargareten** [comment]
Hi, I cannot replicate this can you share your controller?

**Comment by sandervercampt** [comment]
This is my controller function:
` public function users(Request $request, User $user)
    {
        $models = Customer::where('name','like','A%')->paginate()->withQueryString();
        return Inertia::modal('Admin/User/Partials/Customers', ['user' => $user, 'models' => CustomerResource::collection($models)])->baseRoute('users.edit', $user->uuid)->forceBase();
    }`

**Comment by emargareten** [comment]
@sandervercampt thanks, fixed in [v1.0.3](https://github.com/emargareten/inertia-modal/releases/tag/v1.0.3)
