### ISSUE TITLE
Please support inertia-laravel v1.0

### ISSUE THREAD

**Issue by chargoy** [emargareten/inertia-modal#24]
Hi!

The current version 0.6.x does not support inertia-laravel v1.0. The Inertia version is required for Laravel 11 support.

Thanks very much for your work in this library.

**Comment by emargareten** [comment]
[v1.1.0](https://github.com/emargareten/inertia-modal/releases/tag/v1.1.0)

**Comment by emargareten** [comment]
Thanks!

**Comment by chargoy** [comment]
Wow!! that was fast!!! Thank you very much!!
