### ISSUE TITLE
Enhancement: accept `Arrayable`'s in Inertia::modal()

### ISSUE THREAD

**Issue by JasperTey** [emargareten/inertia-modal#25]
A request for an enhancement: to also accept `Arrayable` types when passing the props to `Inertia:modal()`.

Example:

```php
public function edit(Request $request, ContactLog $contact_log)
{
    return Inertia::modal(
        'ContactLog/Edit/Modal',
        EditContactLogViewModel::make($contact_log)->toArray() // <-- currently requires explicit ->toArray()
    )->baseRoute('contact-logs.index');
}
```

This will make the behaviour more seamless and consistent, since Inertia::render() supports it; and also in general wherever things are returned or propagated down from controllers to responses (e.g., Eloquent API Resources).

I happened to stumble upon this as I was swapping a project from momentum-modal to this package, and everything was seamless except for this one aspect.

I can work on a PR for this when I find some time later, but wanted to note this down here for further discussion.

Thoughts?

**Comment by emargareten** [comment]
Which version are you using?

**Comment by JasperTey** [comment]
> Which version are you using?

`emargareten/inertia-modal           v1.1.0`

**Comment by emargareten** [comment]
I am pretty sure this was already implemented in v1.0.4, I'll have a look when I get some time

**Comment by JasperTey** [comment]
> I am pretty sure this was already implemented in v1.0.4, I'll have a look when I get some time

Ah, I will double check on my end as well.

**Comment by emargareten** [comment]
https://github.com/emargareten/inertia-modal/blob/master/src/Modal.php#L219C1-L221C14

**Comment by JasperTey** [comment]
Removing the `->toArray()` in my example above yields the following:

```
TypeError
PHP 8.2.13
10.48.3
Emargareten\InertiaModal\Modal::resolvePropertyInstances(): Argument #1 ($props) must be of type array, Domain\ContactLog\ViewModels\EditContactLogViewModel given, called in 

...vendor/emargareten/inertia-modal/src/Modal.php on line 175
```

It's that `resolvePropertyInstances` doesn't accept Arrayable $props at the top level:

`public function resolvePropertyInstances(array $props, bool $unpackDotProps = true):`

**Comment by emargareten** [comment]
[v1.2.0](https://github.com/emargareten/inertia-modal/releases/tag/v1.2.0)
