### ISSUE TITLE
Behaviour of router.reload() inside a modal

### ISSUE THREAD

**Issue by JasperTey** [emargareten/inertia-modal#29]
Some context: I'm working with a project that was swapped from momentum-modal to this package.

I have a modal, which has an action within it that performs a task and then triggers a `router.reload`:

```js
router.reload({
    preserveScroll: true,
    replace: true,
});
```

In other words, the current URL (a modal route) is being reloaded. When this happens, I'm not seeing expected reloaded data reflected in the modal even though the `router.reload` network request is made.

What I have to do now is:
```js
router.reload({
    preserveScroll: true,
    replace: true,
    onSuccess: () => {
        // Explicitly update things that need to be updated
        form.something = props.payload.something;
    },
});
```

I tried playing with `preserveState`, no difference whether true or false.

Is this a bug, or is there something else I'm missing or misunderstanding about how reloads work?

**Comment by emargareten** [comment]
`router.reload` preserves state by default and cannot be changed, see https://github.com/inertiajs/inertia/blob/c7b329c1ab284c33bace85198615b7b0cc597f3d/packages/core/src/router.ts#L509-L511

**Comment by JasperTey** [comment]
Thanks for clarifying that.

I think then that the momentum-modal package must have different behaviour to begin with, where everything on the page was rehydrated/remounted, hence why my usage of router.reload appeared to refresh the entire state.

Will close this, as this does look to be the correct behaviour by the book.
