### ISSUE TITLE
"Reference Error: document is not defined" when starting Inertia SSR server

### ISSUE THREAD

**Issue by SpeedJack** [emargareten/inertia-modal#30]
https://github.com/emargareten/inertia-modal/blob/02b7ab55fa15c571b128fde3b2a5698dc8f24e0a/js/useModal.js#L15-L18

This line of code is causing `php artisan inertia:start-ssr` to fail. See: https://github.com/inertiajs/inertia/discussions/1849#discussion-6492443

**Comment by emargareten** [comment]
Hi @SpeedJack thanks for reporting, please upgrade to v1.3.0 and let me know if you are still having issues

**Comment by SpeedJack** [comment]
It works now. Thanks!
