### ISSUE TITLE
Inertia 2.0 Support?

### ISSUE THREAD

**Issue by JasperTey** [emargareten/inertia-modal#39]
I was about to try out Inertia 2.0 in a project (https://v2.inertiajs.com/upgrade-guide), but wasn't able to proceed due to the current version constraint: `emargareten/inertia-modal v1.3.0 requires inertiajs/inertia-laravel ^0.6.9|^1.0.0`.

Is this on your roadmap sometime soon? I don't think there'd be any changes to the internals other than updating the version constraint, but I will first attempt on my own using a fork.

**Comment by emargareten** [comment]
Released [v1.4.0](https://github.com/emargareten/inertia-modal/releases/tag/v1.4.0)

Thanks!
